### ISSUE TITLE
Compendium to-do

### ISSUE THREAD

**Issue by diazrenata** [diazrenata/BBSsims#2]
- [x] Copy over fxns from bbs-size-shifts
- [x] Add tests for size-shifts fxns (some already in bbs-size-shifts)
    - [x] fit_trend_models_energy
    - [x] all_models_predicted_change
    - [x] model_predicted_change
    - [x] compare_community_structure
    - [x] fit_gmm
    - [x] add_gmm
    - [x] species data fxns
- [x] Prune fxns here to those used for size-shifts
    - [x] Re-evaluate MATSS + retriever dependencies
- [x] Copy over analysis, reports, manuscript files
- [x] Make sure addt'l files do not break build/tests
- [x] Add README with install and replication instructions
- [x] Put main results files as .RDS files in repo, document column names
- [x] Incorporate skme edits in ms
- [x] Double check numeric values in text and tables
- [x] Copy to temp account, remove names and handles
     - https://www.github.com/bbssizeshifts/BBSsims
